---
# https://hub.docker.com/r/johngong/qbittorrent
# https://github.com/gshang2017/docker/tree/master/qBittorrent

services:
  qbittorrent:
    image: johngong/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 8989:8989
      - 6881:6881
      - 6881:6881/udp
