---
# https://hub.docker.com/_/matomo/
# https://github.com/matomo-org/docker
services:
  matomo:
    container_name: matomo
    env_file:
      - path: ./.env
        required: false
    hostname: matomo
    image: matomo:latest
    ports:
      - 80:80
    restart: unless-stopped
  db:
    env_file:
      - path: ./.env
        required: false
    image: mariadb:latest
    restart: unless-stopped
