---
# http://hub.docker.com/r/joplin/server

services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    hostname: joplin
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    depends_on:
      - postgres
    ports:
      - 22300:22300

  postgres:
    image: postgres:16
    hostname: joplin
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
