---
repos:
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3   # or other specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v6.0.0 # Use a recent stable revision
#   hooks:
#     - id: check-yaml
#     - id: end-of-file-fixer
#     - id: trim-whitespace
