---
repos:
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3   # or other specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.3.0
  #   hooks:
  #     - id: pretty-format-json
  #       types: [file] # override `types: [json]`
  #       files: \.(json|myext)$
