---
# https://hub.docker.com/r/drone/drone
services:
  server:
    container_name: drone-server
    env_file:
      - path: ./.env
        required: false
    hostname: drone
    image: drone/drone:2
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  runner:
    container_name: drone-runner
    depends_on:
      - server
    env_file:
      - path: ./.env
        required: false
    hostname: drone
    image: drone/drone-runner-docker:1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
