---
x-db-credentials: &db-credentials
  # Use the default POSTGRES_ credentials if they're available or simply default to "listmonk"
  # for database user, password, and database name
  POSTGRES_USER: &db-user listmonk
  POSTGRES_PASSWORD: &db-password listmonk
  POSTGRES_DB: &db-name listmonk
services:
  app:
    # listmonk app
    command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
    container_name: listmonk_app
    depends_on:
      - db
    # All LISTMONK_* env variables also support the LISTMONK_*_FILE pattern for loading secrets from files with Docker secrets and Podman
    # eg: LISTMONK_ADMIN_USER -> LISTMONK_ADMIN_USER_FILE=/path/to/file_with_value
    # The same params as in config.toml are passed as env vars here.
    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__user: *db-user
      LISTMONK_db__password: *db-password
      LISTMONK_db__database: *db-name
      LISTMONK_db__host: db
      LISTMONK_db__port: 5432
      LISTMONK_db__ssl_mode: disable
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s
      TZ: Etc/UTC
      # If these (optional) are set during the first `docker compose up`, then the Super Admin user is automatically created.
      # Otherwise, the user can be setup on the web app after the first visit to http://localhost:9000
      LISTMONK_ADMIN_USER: ${LISTMONK_ADMIN_USER:-}
      LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:-}
    hostname: listmonk.example.com # Recommend using FQDN for hostname
    image: listmonk/listmonk:latest
    networks:
      - listmonk
    ports:
      - "9000:9000" # To change the externally exposed port, change to: $custom_port:9000
    restart: unless-stopped
    volumes:
      # --config (file) param is set to empty so that listmonk only uses the env vars (below) for config.
      # --install --idempotent ensures that DB installation happens only once on an empty DB, on the first ever start.
      # --upgrade automatically runs any DB migrations when a new image is pulled.
      # Mount an uploads directory on the host to /listmonk/uploads inside the container.
      # To use this, change directory path in Admin -> Settings -> Media to /listmonk/uploads
      - ./uploads:/listmonk/uploads:rw
  db:
    # Postgres database
    container_name: listmonk_db
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    image: postgres:17-alpine
    networks:
      - listmonk
    ports:
      - "127.0.0.1:5432:5432" # Only bind on the local interface. To connect to Postgres externally, change this to 0.0.0.0
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data
networks:
  listmonk:
volumes:
  listmonk-data:
