---

# https://hub.docker.com/r/linuxserver/openssh-server
services:
  openssh-server:
    image: linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-2222}:2222
    volumes:
    - ./data:/config
