---
# https://hub.docker.com/r/linuxserver/openssh-server
services:
  server:
    container_name: openssh-server
    env_file:
      - path: ./.env
        required: false
    hostname: openssh-server
    image: linuxserver/openssh-server:latest
    ports:
      - 2222:2222
    restart: unless-stopped
