---
services:
  file-downloader:
    image: ghcr.io/idev-sig/file-downloader:dev
    container_name: file-downloader
    hostname: file-downloader
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
