---
services:
  file-downloader:
    container_name: file-downloader
    env_file:
      - path: ./.env
        required: false
    hostname: file-downloader
    image: ghcr.io/idevsig/file-downloader:dev
    restart: unless-stopped
