---
# https://hub.docker.com/r/vaultwarden/server
services:
  vaultwarden:
    container_name: vaultwarden
    env_file:
      - path: ./.env
        required: false
    hostname: vaultwarden
    image: vaultwarden/server:latest
    ports:
      - 80:80
    restart: unless-stopped
