---
# https://hub.docker.com/r/ekzhang/rustpad
services:
  rustpad:
    container_name: rustpad
    env_file:
      - path: ./.env
        required: false
    hostname: rustpad
    image: ghcr.io/forkdo/rustpad:latest
    ports:
      - 3030:3030
    restart: unless-stopped
    user: 0:0
