---
# https://hub.docker.com/r/ekzhang/rustpad

services:
  rustpad:
    image: ghcr.io/forkdo/rustpad:latest
    container_name: rustpad
    hostname: rustpad
    restart: unless-stopped
    user: 0:0
    env_file:
      - path: ./.env
        required: false
    ports:
      - 3030:3030
