---
# https://github.com/getarcaneapp/arcane/pkgs/container/arcane
services:
  arcane:
    container_name: arcane
    env_file:
      - path: ./.env
        required: false
    hostname: arcane
    healthcheck:
      test: ['CMD-SHELL', 'curl -fsS http://localhost:3552/api/health >/dev/null || exit 1']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    image: ghcr.io/getarcaneapp/arcane:latest
    ports:
      - 3552:3552
    restart: unless-stopped
