---

# https://hub.docker.com/r/jetsung/claude-code-router

services:
  claude-code-router:
    image: jetsung/claude-code-router:latest
    container_name: claude-code-router
    hostname: claude-code-router
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 3456:3456
