---
# https://hub.docker.com/r/gotify/server

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    hostname: gotify
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 80:80
    security_opt:
      - no-new-privileges:true

  igotify:
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    container_name: igotify
    hostname: igotify
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    profiles:
      - igotify
