---
# https://hub.docker.com/r/schollz/croc
x-croc-common: &croc-common
  command: ["relay"]
  env_file:
    - path: ./.env
      required: false
  hostname: croc
  image: schollz/croc:latest
  restart: unless-stopped
services:
  croc:
    <<: *croc-common
    container_name: croc
    ports:
      - 9009-9013:9009-9013
    profiles:
      - croc
  server:
    <<: *croc-common
    container_name: croc
    profiles:
      - server
