---
# https://hub.docker.com/r/schollz/croc

services:
  croc:
    image: schollz/croc:latest
    container_name: croc
    hostname: croc
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 9009-9013:9009-9013
    command: ["relay"]

  croc-custom:
    extends:
      service: croc
    container_name: croc-custom
    ports: !override
      - 39009-39013:9009-9013
    profiles:
      - custom
