---
# https://hub.docker.com/r/dpage/pgadmin4/
services:
  pgadmin4:
    container_name: pgadmin
    env_file:
      - path: ./.env
        required: false
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 80:80
    restart: unless-stopped
