---
# https://hub.docker.com/r/dpage/pgadmin4/

services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin4
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 80:80
