---
# https://hub.docker.com/r/gitlab/gitlab-ce
services:
  gitlab:
    container_name: gitlab
    env_file:
      - path: ./.env
        required: false
    hostname: 'gitlab.example.com'
    image: gitlab/gitlab-ce:latest
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    restart: unless-stopped
    shm_size: '256m'

  gitlab-runner:
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
