---
# https://github.com/minio/minio/tree/master/docs/orchestration/docker-compose

services:
  minio:
    image: quay.io/minio/minio:${MINIO_IMAGE_VERSION:-RELEASE.2025-02-18T16-25-55Z}
    container_name: minio
    hostname: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./data:/data
    ports:
      - ${MINIO_SERVER_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
