---
# https://ghcr.io/thilojaeggi/wingetty
services:
  wingetty:
    container_name: wingetty
    env_file:
      - path: ./.env
        required: false
    hostname: wingetty
    image: ghcr.io/thilojaeggi/wingetty:latest
    ports:
      - 8080:8080
    restart: unless-stopped
