---
# https://hub.docker.com/r/zmister/mrdoc

services:
  mrdoc:
    image: zmister/mrdoc:v4
    container_name: mrdoc
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${SERV_PORT}:10086
    volumes:
    - ./MrDoc:/app/MrDoc
