---
# https://hub.docker.com/r/bytemark/webdav

services:
  webdav:
    image: bytemark/webdav:latest
    container_name: webdav
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 80:80
    volumes:
      - ./data:/var/lib/dav
