---
# https://hub.docker.com/_/phpmyadmin
services:
  phpmyadmin:
    container_name: phpmyadmin
    env_file:
      - path: ./.env
        required: false
    hostname: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 80:80
    restart: unless-stopped
