---
# https://hub.docker.com/r/sissbruecker/linkding
services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    hostname: linkding
    restart: unless-stopped
    ports:
      - ${SERV_PORT:-9090}:9090
    volumes:
      - ./data:/etc/linkding/data
