---
# https://docs.gitlab.com/runner/install/docker.html
# - /run/user/1001/docker.sock:/var/run/docker.sock
services:
  gitlab-runner:
    container_name: gitlab-runner
    env_file:
      - path: ./.env
        required: false
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
