---
# https://github.com/forkdo/simple-http-server/pkgs/container/simple-http-server

services:
  simple-http-server:
    image: ghcr.io/forkdo/simple-http-server:latest
    container_name: simple-http-server
    hostname: simple-http-server
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 8000:8000
    command: ["--index"]
