---
# https://github.com/users/thomiceli/packages/container/package/opengist
services:
  opengist:
    image: ghcr.io/thomiceli/opengist:latest
    container_name: opengist
    restart: unless-stopped
    env_file: ../files/.env
    ports:
      - ${SERV_PORT:-6157}:6157
      - ${SSH_PORT:-2222}:2222
    volumes:
      - ./data:/opengist
