---
# https://hub.docker.com/r/finab/bark-server
services:
  bark:
    container_name: bark
    env_file:
      - path: ./.env
        required: false
    hostname: bark
    image: finab/bark-server:latest
    ports:
      - 8080:8080
    restart: unless-stopped
