---
# https://hub.docker.com/r/dutchcoders/transfer.sh
services:
  transfer:
    container_name: transfer
    env_file:
      - path: ./.env
        required: false
    hostname: transfer
    image: dutchcoders/transfer.sh:latest
    ports:
      - 8080:8080
    restart: unless-stopped
