---
# https://hub.docker.com/r/dpage/pgadmin4/
services:
  pgadmin4:
    extends:
      file: ../pgadmin/compose.yaml
      service: pgadmin4
  postgres:
    extends:
      file: ../postgres/compose.yaml
      service: postgres
