---
# https://hub.docker.com/r/cloudflare/cloudflared
services:
  cloudflared:
    command: ["tunnel", "run"]
    container_name: cloudflared
    env_file:
      - path: ./.env
        required: false
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
