---

# https://hub.docker.com/r/jetsung/rclone-backup
services:
  rclone-backup:
    image: jetsung/rclone-backup:latest
    container_name: rclone-backup
    hostname: rclone-backup
    restart: unless-stopped
#     volumes:
#     - ./data:/data
