---
# https://hub.docker.com/r/jetsung/rclone-backup
services:
  rclone-backup:
    container_name: rclone-backup
    env_file:
      - path: ./.env
        required: false
    hostname: rclone-backup
    image: jetsung/rclone-backup:latest
    restart: unless-stopped
