---
# https://github.com/orgs/static-web-server/packages/container/package/static-web-server

services:
  static-web-server:
    image: ghcr.io/static-web-server/static-web-server:latest
    hostname: static-web-server
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    volumes:
      - ./data/downloads:/app/downloads
    ports:
      - 80:80
    command: [--root, /app/downloads, -z]
