---
# https://github.com/orgs/static-web-server/packages/container/package/static-web-server

services:
  static-web-server:
    image: ghcr.io/static-web-server/static-web-server:latest
    container_name: static-web-server
    hostname: server
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 80:80
    command: ["--root", "/app/downloads", "-z"]
