---
# https://quay.io/coreos/etcd

services:
  etcd:
    image: quay.io/coreos/etcd:v3.6.7
    container_name: etcd
    hostname: etcd
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 2379:2379
      - 2380:2380
