---
# https://quay.io/coreos/etcd
services:
  etcd:
    container_name: etcd
    env_file:
      - path: ./.env
        required: false
    hostname: etcd
    image: quay.io/coreos/etcd:v3.6.7
    ports:
      - 2379:2379
      - 2380:2380
    restart: unless-stopped
