---
# https://hub.docker.com/r/umputun/remark42
services:
  remark:
    container_name: remark42
    env_file:
      - path: ./.env
        required: false
    hostname: remark42
    image: umputun/remark42:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
    ports:
      - 8080:8080
    restart: unless-stopped
