---
# https://hub.docker.com/r/neilpang/acme.sh
services:
  acme:
    command: ["daemon"]
    container_name: acme.sh
    env_file:
      - path: ./.env
        required: false
    hostname: acme
    image: neilpang/acme.sh:latest
    restart: unless-stopped
