---
# https://hub.docker.com/r/ferronserver/ferron
x-ferron-common: &ferron-common
  env_file:
    - path: ./.env
      required: false
  image: ferronserver/ferron:2-alpine
  ports:
    - 80:80
    - 443:443
  restart: unless-stopped
  user: 0:0
  volumes:
    - ./ferron.kdl:/etc/ferron.kdl
services:
  ferron:
    <<: *ferron-common
    profiles:
      - ferron
    volumes:
      - ./data/html:/var/www/ferron
  server:
    <<: *ferron-common
    profiles:
      - server
    volumes:
      - ./data/ferron-acme:/var/cache/ferron-acme" # This volume is needed for persistent automatic TLS cache, otherwise the web server will obtain a new certificate on each restart
