---
# https://hub.docker.com/r/messense/aliyundrive-webdav

services:
  webdav:
    image: messense/aliyundrive-webdav:latest
    container_name: aliyundrive-webdav
    hostname: aliyundrive
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 8080:8080
