---
# https://hub.docker.com/r/messense/aliyundrive-webdav
services:
  webdav:
    container_name: aliyundrive-webdav
    env_file:
      - path: ./.env
        required: false
    hostname: aliyundrive
    image: messense/aliyundrive-webdav:latest
    ports:
      - 8080:8080
    restart: unless-stopped
