---
# https://hub.docker.com/_/mysql
services:
  mysql:
    container_name: mysql
    env_file:
      - path: ./.env
        required: false
    image: mysql:latest
    ports:
      - 3306:3306
    restart: unless-stopped
