---
# https://hub.docker.com/r/idevsig/filetas
services:
  filetas:
    container_name: filetas
    env_file:
      - path: ./.env
        required: false
    hostname: filetas
    image: idevsig/filetas:latest
    ports:
      - 8000:8000
    restart: unless-stopped
