---
# https://hub.docker.com/r/neosmemo/memos
services:
  memos:
    container_name: memos
    env_file:
      - path: ./.env
        required: false
    hostname: memos
    image: neosmemo/memos:stable
    ports:
      - 5230:5230
    restart: unless-stopped
