---
# https://hub.docker.com/r/calciumion/new-api
services:
  new-api:
    container_name: new-api
    env_file:
      - path: ./.env
        required: false
    hostname: new-api
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    image: calciumion/new-api:latest
    ports:
      - 3000:3000
    restart: unless-stopped
