---
# https://hub.docker.com/r/wizjin/chanify
services:
  chanify:
    container_name: chanify
    env_file:
      - path: ./.env
        required: false
    hostname: chanify
    image: wizjin/chanify:latest
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./chanify.yaml:/root/.chanify.yml
