---
# https://github.com/chanify/chanify

services:
  chanify:
    image: wizjin/chanify:dev
    container_name: chanify
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${SERV_PORT}:80
    volumes:
    - ./data:/data
    - ./chanify.yml:/root/.chanify.yml
