---
# https://hub.docker.com/r/openlistteam/openlist

services:
  openlist:
    image: openlistteam/openlist:latest
    container_name: openlist
    hostname: openlist
    restart: unless-stopped
    user: '0:0'
    env_file:
      - path: ./.env
        required: false
    ports:
      - 5244:5244

  ocr:
    image: openlistteam/ocr_api_server:main
    container_name: ocr
    hostname: ocr
    restart: unless-stopped
