---
# https://hub.docker.com/r/valeriansaliou/sonic
services:
  sonic:
    container_name: sonic
    env_file:
      - path: ./.env
        required: false
    hostname: sonic
    image: valeriansaliou/sonic:latest
    ports:
      - 1491:1491
    restart: unless-stopped
    volumes:
      - ./config.cfg:/etc/sonic.cfg
