---
# https://hub.docker.com/r/valeriansaliou/sonic

services:
  sonic:
    image: valeriansaliou/sonic:latest
    container_name: sonic
    hostname: sonic
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    ports:
      - 1491:1491
    volumes:
      - ./config.cfg:/etc/sonic.cfg
