---
# https://hub.docker.com/r/syncthing/syncthing
services:
  syncthing:
    container_name: syncthing
    env_file:
      - path: ./.env
        required: false
    hostname: syncthing
    image: syncthing/syncthing:latest
    ports:
      - 8384:8384       # Web UI
      - 22000:22000/tcp       # TCP file transfers
      - 22000:22000/udp       # QUIC file transfers
      - 21027:21027/udp       # Receive local discovery broadcasts
    restart: unless-stopped
