---
# https://github.com/syncthing/syncthing/blob/main/README-Docker.md

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${WEB_PORT}:8384         # Web UI
    - ${SERV_PORT}:22000/tcp         # TCP file transfers
    - ${SERV_PORT}:22000/udp         # QUIC file transfers
    - ${DISCOVERY_PORT}:21027/udp         # Receive local discovery broadcasts
    volumes:
    - ./syncthing:/var/syncthing
