---
# https://hub.docker.com/_/php
services:
  nginx:
    container_name: nginx
    env_file:
      - path: ./.env
        required: false
    hostname: nginx
    image: nginx:alpine
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./data/www:/var/www/html:rw
      - ./conf.d:/etc/nginx/conf.d:rw
  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    image: php:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./data/www:/var/www/html:rw
